#!/usr/bin/env python
#
# License: BSD
#
##############################################################################
# Imports
##############################################################################

import rqt_wrapper
import sys

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    rqt_wrapper = rqt_wrapper.RQTWrapper('rqt_reconfigure.param_plugin.ParamPlugin')
    sys.exit(rqt_wrapper.exec_())
